Welcome to my scratch pad. 

I honestly know nothing about modern pokemon, I only know the OGs. I'm trying to figure out this dataset. Thanks for the patience.

Questions:
 - The heck is a mega pokemon?
 - how does type 2 affect the pokemon in comparison to those with just one type?
 - what will be my predictions...
 - how do I get that e with the slashy on top???

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
#read_csv
df = pd.read_csv('pokedex.csv')

In [3]:
#check csv
df

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,1040,896,Glastrier,Polaross,ブリザポス (Burizaposu),8,Sub Legendary,Wild Horse Pokémon,1,Ice,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
1041,1041,897,Spectrier,Phantoross,レイスポス (Reisuposu),8,Sub Legendary,Swift Horse Pokémon,1,Ghost,...,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
1042,1042,898,Calyrex,Coronospa,バドレックス (Budrex),8,Legendary,King Pokémon,2,Psychic,...,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0
1043,1043,898,Calyrex Ice Rider,Coronospa,バドレックス (Budrex),8,Legendary,High King Pokémon,2,Psychic,...,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0
1044,1044,898,Calyrex Shadow Rider,Coronospa,バドレックス (Budrex),8,Legendary,High King Pokémon,2,Psychic,...,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0

In [4]:
#check for missing values
df.isna().sum()

Unnamed: 0            0
pokedex_number        0
name                  0
german_name           0
japanese_name         0
generation            0
status                0
species               0
type_number           0
type_1                0
type_2              492
height_m              0
weight_kg             1
abilities_number      0
ability_1             3
ability_2           529
ability_hidden      232
total_points          0
hp                    0
attack                0
defense               0
sp_attack             0
sp_defense            0
speed                 0
catch_rate           18
base_friendship     115
base_experience     120
growth_rate           1
egg_type_number       0
egg_type_1            3
egg_type_2          760
percentage_male     173
egg_cycles            1
against_normal        0
against_fire          0
against_water         0
against_electric      0
against_grass         0
against_ice           0
against_fight         0
against_poison        0
against_ground        0
against_flying        0
against_psychic       0
against_bug           0
against_rock          0
against_ghost         0
against_dragon        0
against_dark          0
against_steel         0
against_fairy         0
dtype: int64

In [5]:
#drop columns I know I won't be using
df= df.drop(columns=['Unnamed: 0','german_name','japanese_name'])

In [6]:
df

,pokedex_number,name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,1,Normal,Seed Pokémon,2,Grass,Poison,0.7,6.9,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,1,Normal,Seed Pokémon,2,Grass,Poison,1.0,13.0,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.0,100.0,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,Mega Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.4,155.5,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,Charmander,1,Normal,Lizard Pokémon,1,Fire,NaN,0.6,8.5,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,896,Glastrier,8,Sub Legendary,Wild Horse Pokémon,1,Ice,NaN,2.2,800.0,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
1041,897,Spectrier,8,Sub Legendary,Swift Horse Pokémon,1,Ghost,NaN,2.0,44.5,...,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
1042,898,Calyrex,8,Legendary,King Pokémon,2,Psychic,Grass,1.1,7.7,...,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0
1043,898,Calyrex Ice Rider,8,Legendary,High King Pokémon,2,Psychic,Ice,2.4,809.1,...,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0
1044,898,Calyrex Shadow Rider,8,Legendary,High King Pokémon,2,Psychic,Ghost,2.4,53.6,...,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0

In [7]:
#4 being highest value, 0 being lowest.
df.against_ground.max() - df.against_ground.min()

4.0

In [8]:
#checking to make sure that the max is 4, and the min is 0
df.against_fairy.max() - df.against_fairy.min()

4.0

In [9]:
#Charmander is weak against water, rock, and ground
df.against_fire

0       2.0
1       2.0
2       2.0
3       1.0
4       0.5
       ...
1040    2.0
1041    1.0
1042    2.0
1043    2.0
1044    1.0
Name: against_fire, Length: 1045, dtype: float64

In [10]:
#the higher the against_? is, the more sensitive they are to it (bad thing)

In [11]:
#waaaaaaaazah
df.species=='Seed Pokémon'

0        True
1        True
2        True
3        True
4       False
        ...
1040    False
1041    False
1042    False
1043    False
1044    False
Name: species, Length: 1045, dtype: bool

In [12]:
#let's go back to nulls
df.isna().sum()

pokedex_number        0
name                  0
generation            0
status                0
species               0
type_number           0
type_1                0
type_2              492
height_m              0
weight_kg             1
abilities_number      0
ability_1             3
ability_2           529
ability_hidden      232
total_points          0
hp                    0
attack                0
defense               0
sp_attack             0
sp_defense            0
speed                 0
catch_rate           18
base_friendship     115
base_experience     120
growth_rate           1
egg_type_number       0
egg_type_1            3
egg_type_2          760
percentage_male     173
egg_cycles            1
against_normal        0
against_fire          0
against_water         0
against_electric      0
against_grass         0
against_ice           0
against_fight         0
against_poison        0
against_ground        0
against_flying        0
against_psychic       0
against_bug           0
against_rock          0
against_ghost         0
against_dragon        0
against_dark          0
against_steel         0
against_fairy         0
dtype: int64

In [13]:
#for type2 we will fill in the nulls with none
df['type_2'].fillna('None', inplace=True)

In [14]:
#check for columns with null values, and how many there are
null_columns=df.columns[df.isnull().any()]
df[null_columns].isnull().sum()

weight_kg            1
ability_1            3
ability_2          529
ability_hidden     232
catch_rate          18
base_friendship    115
base_experience    120
growth_rate          1
egg_type_1           3
egg_type_2         760
percentage_male    173
egg_cycles           1
dtype: int64

In [15]:
#Whoever entry 1033 is...
print(df[df["weight_kg"].isnull()][null_columns])

      weight_kg ability_1 ability_2 ability_hidden  catch_rate  \
1033        NaN       NaN       NaN            NaN         NaN

      base_friendship  base_experience growth_rate    egg_type_1 egg_type_2  \
1033              NaN              NaN        Slow  Undiscovered        NaN

      percentage_male  egg_cycles
1033              NaN       120.0

In [16]:
#no weight data on it, let's drop

In [17]:
df.isna().sum()

pokedex_number        0
name                  0
generation            0
status                0
species               0
type_number           0
type_1                0
type_2                0
height_m              0
weight_kg             1
abilities_number      0
ability_1             3
ability_2           529
ability_hidden      232
total_points          0
hp                    0
attack                0
defense               0
sp_attack             0
sp_defense            0
speed                 0
catch_rate           18
base_friendship     115
base_experience     120
growth_rate           1
egg_type_number       0
egg_type_1            3
egg_type_2          760
percentage_male     173
egg_cycles            1
against_normal        0
against_fire          0
against_water         0
against_electric      0
against_grass         0
against_ice           0
against_fight         0
against_poison        0
against_ground        0
against_flying        0
against_psychic       0
against_bug           0
against_rock          0
against_ghost         0
against_dragon        0
against_dark          0
against_steel         0
against_fairy         0
dtype: int64

In [18]:
#there are duplicate pokedex numbers, but since the pokemons are differnt enough let's not do this.
# df.set_index('pokedex_number',inplace=True)

In [19]:
#no ability scrubs
df[df["ability_1"].isnull()][null_columns]

,weight_kg,ability_1,ability_2,ability_hidden,catch_rate,base_friendship,base_experience,growth_rate,egg_type_1,egg_type_2,percentage_male,egg_cycles
33,6.0,NaN,NaN,Lightning Rod,190.0,70.0,112.0,Medium Fast,NaN,NaN,50.0,10.0
172,6.5,NaN,NaN,Anticipation,45.0,70.0,65.0,Medium Fast,NaN,NaN,87.5,35.0
1033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0

In [20]:
#dropping the no ability scrubs
df = df.drop([33, 172,1033])

In [21]:
#what nulls are left
df.isna().sum()

pokedex_number        0
name                  0
generation            0
status                0
species               0
type_number           0
type_1                0
type_2                0
height_m              0
weight_kg             0
abilities_number      0
ability_1             0
ability_2           526
ability_hidden      231
total_points          0
hp                    0
attack                0
defense               0
sp_attack             0
sp_defense            0
speed                 0
catch_rate           17
base_friendship     114
base_experience     119
growth_rate           1
egg_type_number       0
egg_type_1            1
egg_type_2          757
percentage_male     172
egg_cycles            1
against_normal        0
against_fire          0
against_water         0
against_electric      0
against_grass         0
against_ice           0
against_fight         0
against_poison        0
against_ground        0
against_flying        0
against_psychic       0
against_bug           0
against_rock          0
against_ghost         0
against_dragon        0
against_dark          0
against_steel         0
against_fairy         0
dtype: int64

In [22]:
df.shape

(1042, 48)

In [23]:
#nulls in ability_2
df[df["ability_2"].isnull()][null_columns]

,weight_kg,ability_1,ability_2,ability_hidden,catch_rate,base_friendship,base_experience,growth_rate,egg_type_1,egg_type_2,percentage_male,egg_cycles
0,6.9,Overgrow,NaN,Chlorophyll,45.0,70.0,64.0,Medium Slow,Grass,Monster,87.5,20.0
1,13.0,Overgrow,NaN,Chlorophyll,45.0,70.0,142.0,Medium Slow,Grass,Monster,87.5,20.0
2,100.0,Overgrow,NaN,Chlorophyll,45.0,70.0,236.0,Medium Slow,Grass,Monster,87.5,20.0
3,155.5,Thick Fat,NaN,NaN,45.0,70.0,281.0,Medium Slow,Grass,Monster,87.5,20.0
4,8.5,Blaze,NaN,Solar Power,45.0,70.0,62.0,Medium Slow,Dragon,Monster,87.5,20.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1040,800.0,Chilling Neigh,NaN,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1041,44.5,Grim Neigh,NaN,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1042,7.7,Unnerve,NaN,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1043,809.1,As One,NaN,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1044,53.6,As One,NaN,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0

In [24]:
#since they don't have a second ability, fill in with none.
df['ability_2'].fillna('None', inplace=True)

In [25]:
#hidden ability nulls
df[df["ability_hidden"].isnull()][null_columns]

,weight_kg,ability_1,ability_2,ability_hidden,catch_rate,base_friendship,base_experience,growth_rate,egg_type_1,egg_type_2,percentage_male,egg_cycles
3,155.5,Thick Fat,None,NaN,45.0,70.0,281.0,Medium Slow,Grass,Monster,87.5,20.0
7,110.5,Tough Claws,None,NaN,45.0,70.0,285.0,Medium Slow,Dragon,Monster,87.5,20.0
8,100.5,Drought,None,NaN,45.0,70.0,285.0,Medium Slow,Dragon,Monster,87.5,20.0
12,101.1,Mega Launcher,None,NaN,45.0,70.0,284.0,Medium Slow,Monster,Water 1,87.5,20.0
14,9.9,Shed Skin,None,NaN,120.0,70.0,72.0,Medium Fast,Bug,NaN,50.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1040,800.0,Chilling Neigh,None,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1041,44.5,Grim Neigh,None,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1042,7.7,Unnerve,None,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1043,809.1,As One,None,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1044,53.6,As One,None,NaN,3.0,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0

In [26]:
#since they don't have hidden abilities, let's just be honest about it. 
df['ability_hidden'].fillna('None', inplace=True)

In [27]:
#null catch rates must mean they cannot be caught?
df[df["catch_rate"].isnull()][null_columns]

,weight_kg,ability_1,ability_2,ability_hidden,catch_rate,base_friendship,base_experience,growth_rate,egg_type_1,egg_type_2,percentage_male,egg_cycles
69,7.5,Pickup,Tough Claws,Unnerve,NaN,NaN,NaN,Medium Fast,Field,NaN,NaN,20.0
100,24.0,Run Away,Pastel Veil,Anticipation,NaN,NaN,NaN,Medium Fast,Field,NaN,NaN,20.0
102,80.0,Run Away,Pastel Veil,Anticipation,NaN,NaN,NaN,Medium Fast,Field,NaN,NaN,20.0
111,42.0,Steadfast,None,Scrappy,NaN,NaN,NaN,Medium Fast,Field,Flying,NaN,20.0
144,16.0,Levitate,Neutralizing Gas,Misty Surge,NaN,NaN,NaN,Medium Fast,Amorphous,NaN,NaN,20.0
158,56.8,Vital Spirit,Screen Cleaner,Ice Body,NaN,NaN,NaN,Medium Fast,Human-Like,NaN,NaN,25.0
273,0.5,Weak Armor,None,Cursed Body,NaN,NaN,NaN,Fast,Water 1,Water 3,NaN,20.0
320,17.5,Pickup,Gluttony,Quick Feet,NaN,NaN,NaN,Medium Fast,Field,NaN,NaN,15.0
322,32.5,Pickup,Gluttony,Quick Feet,NaN,NaN,NaN,Medium Fast,Field,NaN,NaN,15.0
654,40.0,Hustle,None,Inner Focus,NaN,NaN,NaN,Medium Slow,Field,NaN,NaN,20.0
657,120.0,Gorilla Tactics,None,Zen Mode,NaN,NaN,NaN,Medium Slow,Field,NaN,NaN,20.0
658,120.0,Gorilla Tactics,None,Zen Mode,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
666,1.5,Wandering Spirit,None,None,NaN,NaN,NaN,Medium Fast,Amorphous,Mineral,NaN,25.0
723,20.5,Mimicry,None,None,NaN,NaN,NaN,Medium Fast,Amorphous,Water 1,NaN,20.0
1017,3.0,Hunger Switch,None,None,NaN,NaN,NaN,Medium Fast,Fairy,Field,50.0,10.0
1029,110.0,Intrepid Sword,None,None,NaN,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0
1031,210.0,Dauntless Shield,None,None,NaN,NaN,NaN,Slow,Undiscovered,NaN,NaN,120.0

In [28]:
df.head(70)

,pokedex_number,name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,1,Normal,Seed Pokémon,2,Grass,Poison,0.7,6.9,...,1.0,2.0,2.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,1,Normal,Seed Pokémon,2,Grass,Poison,1.0,13.0,...,1.0,2.0,2.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5
2,3,Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.0,100.0,...,1.0,2.0,2.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5
3,3,Mega Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.4,155.5,...,1.0,2.0,2.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5
4,4,Charmander,1,Normal,Lizard Pokémon,1,Fire,None,0.6,8.5,...,2.0,1.0,1.0,0.5,2.00,1.0,1.0,1.0,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,51,Alolan Dugtrio,1,Normal,Mole Pokémon,2,Ground,Steel,0.7,66.6,...,2.0,0.5,0.5,0.5,0.25,1.0,0.5,1.0,0.5,0.5
67,52,Meowth,1,Normal,Scratch Cat Pokémon,1,Normal,None,0.4,4.2,...,1.0,1.0,1.0,1.0,1.00,0.0,1.0,1.0,1.0,1.0
68,52,Alolan Meowth,1,Normal,Scratch Cat Pokémon,1,Dark,None,0.4,4.2,...,1.0,1.0,0.0,2.0,1.00,0.5,1.0,0.5,1.0,2.0
69,52,Galarian Meowth,1,Normal,Scratch Cat Pokémon,1,Steel,None,0.4,7.5,...,2.0,0.5,0.5,0.5,0.50,1.0,0.5,1.0,0.5,0.5
70,53,Persian,1,Normal,Classy Cat Pokémon,1,Normal,None,1.0,32.0,...,1.0,1.0,1.0,1.0,1.00,0.0,1.0,1.0,1.0,1.0

In [29]:
#well if they can't be caught isn't it just 0? They're not catchable...
df['catch_rate'].fillna(0, inplace=True)

In [30]:
#let's see what's left here
df.isna().sum()

pokedex_number        0
name                  0
generation            0
status                0
species               0
type_number           0
type_1                0
type_2                0
height_m              0
weight_kg             0
abilities_number      0
ability_1             0
ability_2             0
ability_hidden        0
total_points          0
hp                    0
attack                0
defense               0
sp_attack             0
sp_defense            0
speed                 0
catch_rate            0
base_friendship     114
base_experience     119
growth_rate           1
egg_type_number       0
egg_type_1            1
egg_type_2          757
percentage_male     172
egg_cycles            1
against_normal        0
against_fire          0
against_water         0
against_electric      0
against_grass         0
against_ice           0
against_fight         0
against_poison        0
against_ground        0
against_flying        0
against_psychic       0
against_bug           0
against_rock          0
against_ghost         0
against_dragon        0
against_dark          0
against_steel         0
against_fairy         0
dtype: int64

In [31]:
#max base friendship
df['base_friendship'].max()

140.0

In [32]:
#if there is no base friendship among capture, there is no base friendship at all.
df['base_friendship'].fillna(0, inplace=True)

In [33]:
#same for experience
df['base_experience'].fillna(0, inplace=True)

In [34]:
#who in tarnation is not growing???? oh.
df[df["growth_rate"].isnull()][null_columns]

,weight_kg,ability_1,ability_2,ability_hidden,catch_rate,base_friendship,base_experience,growth_rate,egg_type_1,egg_type_2,percentage_male,egg_cycles
658,120.0,Gorilla Tactics,None,Zen Mode,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN

In [35]:
#let's see the growth rates
df['growth_rate'].value_counts()

Medium Fast    433
Slow           255
Medium Slow    245
Fast            68
Erratic         26
Fluctuating     14
Name: growth_rate, dtype: int64

In [36]:
#well...I guess there is no growth rate.
df['growth_rate'].fillna('None', inplace=True)

In [37]:
#there it is
df['growth_rate'].value_counts()

Medium Fast    433
Slow           255
Medium Slow    245
Fast            68
Erratic         26
Fluctuating     14
None             1
Name: growth_rate, dtype: int64

In [38]:
#egg types
df[df["egg_type_1"].isnull()][null_columns]

,weight_kg,ability_1,ability_2,ability_hidden,catch_rate,base_friendship,base_experience,growth_rate,egg_type_1,egg_type_2,percentage_male,egg_cycles
658,120.0,Gorilla Tactics,None,Zen Mode,0.0,0.0,0.0,None,NaN,NaN,NaN,NaN

In [39]:
#this pokemon is a little weird, wonder who it is. Just filling in with nones.
df['egg_type_1'].fillna('None', inplace=True)

In [40]:
#and here too
df['egg_type_2'].fillna('None', inplace=True)

In [41]:
#hmm...I don't want to drop all the genderless pokemon. I don't think gender is going to play a big role so I'll just ruin the integer column
df['percentage_male'].fillna('Genderless', inplace=True)

In [42]:
#haha
df['percentage_male'].value_counts()

50.0          621
Genderless    172
87.5          131
0.0            37
25.0           32
100.0          29
75.0           20
Name: percentage_male, dtype: int64

In [43]:
#the rest of the data types look good 
df.dtypes

pokedex_number        int64
name                 object
generation            int64
status               object
species              object
type_number           int64
type_1               object
type_2               object
height_m            float64
weight_kg           float64
abilities_number      int64
ability_1            object
ability_2            object
ability_hidden       object
total_points          int64
hp                    int64
attack                int64
defense               int64
sp_attack             int64
sp_defense            int64
speed                 int64
catch_rate          float64
base_friendship     float64
base_experience     float64
growth_rate          object
egg_type_number       int64
egg_type_1           object
egg_type_2           object
percentage_male      object
egg_cycles          float64
against_normal      float64
against_fire        float64
against_water       float64
against_electric    float64
against_grass       float64
against_ice         float64
against_fight       float64
against_poison      float64
against_ground      float64
against_flying      float64
against_psychic     float64
against_bug         float64
against_rock        float64
against_ghost       float64
against_dragon      float64
against_dark        float64
against_steel       float64
against_fairy       float64
dtype: object

In [44]:
#ugh it's you again, we get it.
df[df["egg_cycles"].isnull()][null_columns]

,weight_kg,ability_1,ability_2,ability_hidden,catch_rate,base_friendship,base_experience,growth_rate,egg_type_1,egg_type_2,percentage_male,egg_cycles
658,120.0,Gorilla Tactics,None,Zen Mode,0.0,0.0,0.0,None,None,None,Genderless,NaN

In [45]:
#if you don't have an egg cycle...
df['egg_cycles'].value_counts()

20.0     546
15.0     169
120.0    100
25.0      83
40.0      52
30.0      27
10.0      25
35.0      19
80.0      17
5.0        3
Name: egg_cycles, dtype: int64

In [46]:
#you get no egg cycle.
df['egg_cycles'].fillna(0, inplace=True)

In [47]:
#are all NaN values taken care of
df.isna().sum().sum()

0

In [48]:
#hmm
df.head(34)

,pokedex_number,name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,1,Normal,Seed Pokémon,2,Grass,Poison,0.7,6.9,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,1,Normal,Seed Pokémon,2,Grass,Poison,1.0,13.0,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.0,100.0,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
3,3,Mega Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.4,155.5,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
4,4,Charmander,1,Normal,Lizard Pokémon,1,Fire,None,0.6,8.5,...,2.0,1.0,1.0,0.50,2.0,1.0,1.0,1.0,0.5,0.5
5,5,Charmeleon,1,Normal,Flame Pokémon,1,Fire,None,1.1,19.0,...,2.0,1.0,1.0,0.50,2.0,1.0,1.0,1.0,0.5,0.5
6,6,Charizard,1,Normal,Flame Pokémon,2,Fire,Flying,1.7,90.5,...,0.0,1.0,1.0,0.25,4.0,1.0,1.0,1.0,0.5,0.5
7,6,Mega Charizard X,1,Normal,Flame Pokémon,2,Fire,Dragon,1.7,110.5,...,2.0,1.0,1.0,0.50,2.0,1.0,2.0,1.0,0.5,1.0
8,6,Mega Charizard Y,1,Normal,Flame Pokémon,2,Fire,Flying,1.7,100.5,...,0.0,1.0,1.0,0.25,4.0,1.0,1.0,1.0,0.5,0.5
9,7,Squirtle,1,Normal,Tiny Turtle Pokémon,1,Water,None,0.5,9.0,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
10,8,Wartortle,1,Normal,Turtle Pokémon,1,Water,None,1.0,22.5,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
11,9,Blastoise,1,Normal,Shellfish Pokémon,1,Water,None,1.6,85.5,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
12,9,Mega Blastoise,1,Normal,Shellfish Pokémon,1,Water,None,1.6,101.1,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
13,10,Caterpie,1,Normal,Worm Pokémon,1,Bug,None,0.3,2.9,...,0.5,2.0,1.0,1.00,2.0,1.0,1.0,1.0,1.0,1.0
14,11,Metapod,1,Normal,Cocoon Pokémon,1,Bug,None,0.7,9.9,...,0.5,2.0,1.0,1.00,2.0,1.0,1.0,1.0,1.0,1.0
15,12,Butterfree,1,Normal,Butterfly Pokémon,2,Bug,Flying,1.1,32.0,...,0.0,2.0,1.0,0.50,4.0,1.0,1.0,1.0,1.0,1.0
16,13,Weedle,1,Normal,Hairy Bug Pokémon,2,Bug,Poison,0.3,3.2,...,1.0,2.0,2.0,0.50,2.0,1.0,1.0,1.0,1.0,0.5
17,14,Kakuna,1,Normal,Cocoon Pokémon,2,Bug,Poison,0.6,10.0,...,1.0,2.0,2.0,0.50,2.0,1.0,1.0,1.0,1.0,0.5
18,15,Beedrill,1,Normal,Poison Bee Pokémon,2,Bug,Poison,1.0,29.5,...,1.0,2.0,2.0,0.50,2.0,1.0,1.0,1.0,1.0,0.5
19,15,Mega Beedrill,1,Normal,Poison Bee Pokémon,2,Bug,Poison,1.4,40.5,...,1.0,2.0,2.0,0.50,2.0,1.0,1.0,1.0,1.0,0.5
20,16,Pidgey,1,Normal,Tiny Bird Pokémon,2,Normal,Flying,0.3,1.8,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
21,17,Pidgeotto,1,Normal,Bird Pokémon,2,Normal,Flying,1.1,30.0,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
22,18,Pidgeot,1,Normal,Bird Pokémon,2,Normal,Flying,1.5,39.5,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
23,18,Mega Pidgeot,1,Normal,Bird Pokémon,2,Normal,Flying,2.2,50.5,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
24,19,Rattata,1,Normal,Mouse Pokémon,1,Normal,None,0.3,3.5,...,1.0,1.0,1.0,1.00,1.0,0.0,1.0,1.0,1.0,1.0
25,19,Alolan Rattata,1,Normal,Mouse Pokémon,2,Dark,Normal,0.3,3.8,...,1.0,1.0,0.0,2.00,1.0,0.0,1.0,0.5,1.0,2.0
26,20,Raticate,1,Normal,Mouse Pokémon,1,Normal,None,0.7,18.5,...,1.0,1.0,1.0,1.00,1.0,0.0,1.0,1.0,1.0,1.0
27,20,Alolan Raticate,1,Normal,Mouse Pokémon,2,Dark,Normal,0.7,25.5,...,1.0,1.0,0.0,2.00,1.0,0.0,1.0,0.5,1.0,2.0
28,21,Spearow,1,Normal,Tiny Bird Pokémon,2,Normal,Flying,0.3,2.0,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
29,22,Fearow,1,Normal,Beak Pokémon,2,Normal,Flying,1.2,38.0,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
30,23,Ekans,1,Normal,Snake Pokémon,1,Poison,None,2.0,6.9,...,2.0,1.0,2.0,0.50,1.0,1.0,1.0,1.0,1.0,0.5
31,24,Arbok,1,Normal,Cobra Pokémon,1,Poison,None,3.5,65.0,...,2.0,1.0,2.0,0.50,1.0,1.0,1.0,1.0,1.0,0.5
32,25,Pikachu,1,Normal,Mouse Pokémon,1,Electric,None,0.4,6.0,...,2.0,0.5,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
34,26,Raichu,1,Normal,Mouse Pokémon,1,Electric,None,0.8,30.0,...,2.0,0.5,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0

In [49]:
#let's reset the index
df = df.reset_index(drop=True)

In [50]:
#better
df.head(35)

,pokedex_number,name,generation,status,species,type_number,type_1,type_2,height_m,weight_kg,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,1,Bulbasaur,1,Normal,Seed Pokémon,2,Grass,Poison,0.7,6.9,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
1,2,Ivysaur,1,Normal,Seed Pokémon,2,Grass,Poison,1.0,13.0,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
2,3,Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.0,100.0,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
3,3,Mega Venusaur,1,Normal,Seed Pokémon,2,Grass,Poison,2.4,155.5,...,1.0,2.0,2.0,1.00,1.0,1.0,1.0,1.0,1.0,0.5
4,4,Charmander,1,Normal,Lizard Pokémon,1,Fire,None,0.6,8.5,...,2.0,1.0,1.0,0.50,2.0,1.0,1.0,1.0,0.5,0.5
5,5,Charmeleon,1,Normal,Flame Pokémon,1,Fire,None,1.1,19.0,...,2.0,1.0,1.0,0.50,2.0,1.0,1.0,1.0,0.5,0.5
6,6,Charizard,1,Normal,Flame Pokémon,2,Fire,Flying,1.7,90.5,...,0.0,1.0,1.0,0.25,4.0,1.0,1.0,1.0,0.5,0.5
7,6,Mega Charizard X,1,Normal,Flame Pokémon,2,Fire,Dragon,1.7,110.5,...,2.0,1.0,1.0,0.50,2.0,1.0,2.0,1.0,0.5,1.0
8,6,Mega Charizard Y,1,Normal,Flame Pokémon,2,Fire,Flying,1.7,100.5,...,0.0,1.0,1.0,0.25,4.0,1.0,1.0,1.0,0.5,0.5
9,7,Squirtle,1,Normal,Tiny Turtle Pokémon,1,Water,None,0.5,9.0,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
10,8,Wartortle,1,Normal,Turtle Pokémon,1,Water,None,1.0,22.5,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
11,9,Blastoise,1,Normal,Shellfish Pokémon,1,Water,None,1.6,85.5,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
12,9,Mega Blastoise,1,Normal,Shellfish Pokémon,1,Water,None,1.6,101.1,...,1.0,1.0,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
13,10,Caterpie,1,Normal,Worm Pokémon,1,Bug,None,0.3,2.9,...,0.5,2.0,1.0,1.00,2.0,1.0,1.0,1.0,1.0,1.0
14,11,Metapod,1,Normal,Cocoon Pokémon,1,Bug,None,0.7,9.9,...,0.5,2.0,1.0,1.00,2.0,1.0,1.0,1.0,1.0,1.0
15,12,Butterfree,1,Normal,Butterfly Pokémon,2,Bug,Flying,1.1,32.0,...,0.0,2.0,1.0,0.50,4.0,1.0,1.0,1.0,1.0,1.0
16,13,Weedle,1,Normal,Hairy Bug Pokémon,2,Bug,Poison,0.3,3.2,...,1.0,2.0,2.0,0.50,2.0,1.0,1.0,1.0,1.0,0.5
17,14,Kakuna,1,Normal,Cocoon Pokémon,2,Bug,Poison,0.6,10.0,...,1.0,2.0,2.0,0.50,2.0,1.0,1.0,1.0,1.0,0.5
18,15,Beedrill,1,Normal,Poison Bee Pokémon,2,Bug,Poison,1.0,29.5,...,1.0,2.0,2.0,0.50,2.0,1.0,1.0,1.0,1.0,0.5
19,15,Mega Beedrill,1,Normal,Poison Bee Pokémon,2,Bug,Poison,1.4,40.5,...,1.0,2.0,2.0,0.50,2.0,1.0,1.0,1.0,1.0,0.5
20,16,Pidgey,1,Normal,Tiny Bird Pokémon,2,Normal,Flying,0.3,1.8,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
21,17,Pidgeotto,1,Normal,Bird Pokémon,2,Normal,Flying,1.1,30.0,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
22,18,Pidgeot,1,Normal,Bird Pokémon,2,Normal,Flying,1.5,39.5,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
23,18,Mega Pidgeot,1,Normal,Bird Pokémon,2,Normal,Flying,2.2,50.5,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
24,19,Rattata,1,Normal,Mouse Pokémon,1,Normal,None,0.3,3.5,...,1.0,1.0,1.0,1.00,1.0,0.0,1.0,1.0,1.0,1.0
25,19,Alolan Rattata,1,Normal,Mouse Pokémon,2,Dark,Normal,0.3,3.8,...,1.0,1.0,0.0,2.00,1.0,0.0,1.0,0.5,1.0,2.0
26,20,Raticate,1,Normal,Mouse Pokémon,1,Normal,None,0.7,18.5,...,1.0,1.0,1.0,1.00,1.0,0.0,1.0,1.0,1.0,1.0
27,20,Alolan Raticate,1,Normal,Mouse Pokémon,2,Dark,Normal,0.7,25.5,...,1.0,1.0,0.0,2.00,1.0,0.0,1.0,0.5,1.0,2.0
28,21,Spearow,1,Normal,Tiny Bird Pokémon,2,Normal,Flying,0.3,2.0,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
29,22,Fearow,1,Normal,Beak Pokémon,2,Normal,Flying,1.2,38.0,...,0.0,1.0,1.0,0.50,2.0,0.0,1.0,1.0,1.0,1.0
30,23,Ekans,1,Normal,Snake Pokémon,1,Poison,None,2.0,6.9,...,2.0,1.0,2.0,0.50,1.0,1.0,1.0,1.0,1.0,0.5
31,24,Arbok,1,Normal,Cobra Pokémon,1,Poison,None,3.5,65.0,...,2.0,1.0,2.0,0.50,1.0,1.0,1.0,1.0,1.0,0.5
32,25,Pikachu,1,Normal,Mouse Pokémon,1,Electric,None,0.4,6.0,...,2.0,0.5,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
33,26,Raichu,1,Normal,Mouse Pokémon,1,Electric,None,0.8,30.0,...,2.0,0.5,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0
34,26,Alolan Raichu,1,Normal,Mouse Pokémon,2,Electric,Psychic,0.7,21.0,...,2.0,0.5,1.0,1.00,1.0,1.0,1.0,1.0,0.5,1.0

In [51]:
#all NaNs taken care of. 
df.isna().sum().sum()

0